"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.walk = exports.SupportStatement = exports.Release = exports.query = exports.Feature = exports.feature = exports.Compat = exports.Browser = exports.browser = void 0;
const browser_js_1 = require("./browser.js");
Object.defineProperty(exports, "browser", { enumerable: true, get: function () { return browser_js_1.browser; } });
Object.defineProperty(exports, "Browser", { enumerable: true, get: function () { return browser_js_1.Browser; } });
const compat_js_1 = require("./compat.js");
Object.defineProperty(exports, "Compat", { enumerable: true, get: function () { return compat_js_1.Compat; } });
const feature_js_1 = require("./feature.js");
Object.defineProperty(exports, "feature", { enumerable: true, get: function () { return feature_js_1.feature; } });
Object.defineProperty(exports, "Feature", { enumerable: true, get: function () { return feature_js_1.Feature; } });
const query_js_1 = require("./query.js");
Object.defineProperty(exports, "query", { enumerable: true, get: function () { return query_js_1.query; } });
const release_js_1 = require("./release.js");
Object.defineProperty(exports, "Release", { enumerable: true, get: function () { return release_js_1.Release; } });
const supportStatements_js_1 = require("./supportStatements.js");
Object.defineProperty(exports, "SupportStatement", { enumerable: true, get: function () { return supportStatements_js_1.SupportStatement; } });
const walk_js_1 = require("./walk.js");
Object.defineProperty(exports, "walk", { enumerable: true, get: function () { return walk_js_1.walk; } });
